### ISSUE TITLE
Wrong semi-final line-up

### ISSUE THREAD

**Issue by agbarnett** [ekstroem/socceR2018#1]
I think the semi-final pairings are wrong in `simulate_tournament` and should be:
`semi_matches <- cbind(quarter_winners[c(1,2)], quarter_winners[c(3,4)])`
I noticed this when I got a semi-final of Australia vs Denmark, which is a nice thought but impossible as they are in the same group.

**Comment by ekstroem** [comment]
You're right! &#%€/&%# . Nicely spotted.

Australia and Denmark will have to meet in the finals instead (oh and I'll give a beer if you're attending useR next month).

**Comment by agbarnett** [comment]
Thanks. I'll be there and look forward to a beer and a 1:2 Australia:Denmark finish in group C.
